import type { LucideIcon } from "lucide-react";
import {
  Check,
  Shield,
  Zap,
  Star,
  Award,
  Lock,
  Unlock,
  Eye,
  Heart,
  ThumbsUp,
  Target,
  Rocket,
  Crown,
  Diamond,
  Sparkles,
  Monitor,
  Cpu,
  HardDrive,
  Keyboard,
  Mouse,
  Headphones,
  Wifi,
  Bluetooth,
  Power,
  Battery,
  Settings,
  Cog,
  Wrench,
  Package,
  File,
  Folder,
  Image,
  Video,
  Music,
  Download,
  Upload,
  Search,
  Filter,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Camera,
  Mic,
  MicOff,
  Radio,
  Tv,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wind,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Wallet,
  Bookmark,
  Flag,
  Tag,
  Tags,
  Info,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  HelpCircle,
  Lightbulb,
  Brain,
  Key,
  Database,
  Server,
  Code,
  Terminal,
  Laptop,
  Smartphone,
  Tablet,
  Printer,
  Webcam,
} from "lucide-react";

export type PopularIconEntry = { name: string; icon: LucideIcon; category: string };

export const POPULAR_ICONS: PopularIconEntry[] = [
  { name: "Check", icon: Check, category: "Features" },
  { name: "Shield", icon: Shield, category: "Security" },
  { name: "Zap", icon: Zap, category: "Performance" },
  { name: "Star", icon: Star, category: "Quality" },
  { name: "Award", icon: Award, category: "Achievement" },
  { name: "Lock", icon: Lock, category: "Security" },
  { name: "Unlock", icon: Unlock, category: "Access" },
  { name: "Eye", icon: Eye, category: "Visibility" },
  { name: "Heart", icon: Heart, category: "Favorite" },
  { name: "ThumbsUp", icon: ThumbsUp, category: "Approval" },
  { name: "Target", icon: Target, category: "Precision" },
  { name: "Rocket", icon: Rocket, category: "Speed" },
  { name: "Crown", icon: Crown, category: "Premium" },
  { name: "Diamond", icon: Diamond, category: "Premium" },
  { name: "Sparkles", icon: Sparkles, category: "Enhancement" },
  { name: "Lightbulb", icon: Lightbulb, category: "Innovation" },
  { name: "Brain", icon: Brain, category: "Intelligence" },
  { name: "Key", icon: Key, category: "Access" },
  { name: "Monitor", icon: Monitor, category: "Hardware" },
  { name: "Cpu", icon: Cpu, category: "Hardware" },
  { name: "HardDrive", icon: HardDrive, category: "Storage" },
  { name: "Keyboard", icon: Keyboard, category: "Input" },
  { name: "Mouse", icon: Mouse, category: "Input" },
  { name: "Headphones", icon: Headphones, category: "Audio" },
  { name: "Webcam", icon: Webcam, category: "Hardware" },
  { name: "Printer", icon: Printer, category: "Hardware" },
  { name: "Camera", icon: Camera, category: "Hardware" },
  { name: "Mic", icon: Mic, category: "Audio" },
  { name: "MicOff", icon: MicOff, category: "Audio" },
  { name: "Wifi", icon: Wifi, category: "Network" },
  { name: "Bluetooth", icon: Bluetooth, category: "Network" },
  { name: "Power", icon: Power, category: "System" },
  { name: "Battery", icon: Battery, category: "Power" },
  { name: "Settings", icon: Settings, category: "Tools" },
  { name: "Cog", icon: Cog, category: "Configuration" },
  { name: "Wrench", icon: Wrench, category: "Tools" },
  { name: "Package", icon: Package, category: "Software" },
  { name: "Code", icon: Code, category: "Development" },
  { name: "Terminal", icon: Terminal, category: "Development" },
  { name: "Database", icon: Database, category: "Data" },
  { name: "Server", icon: Server, category: "Infrastructure" },
  { name: "Laptop", icon: Laptop, category: "Devices" },
  { name: "Smartphone", icon: Smartphone, category: "Devices" },
  { name: "Tablet", icon: Tablet, category: "Devices" },
  { name: "Radio", icon: Radio, category: "Devices" },
  { name: "Tv", icon: Tv, category: "Devices" },
  { name: "File", icon: File, category: "Files" },
  { name: "Folder", icon: Folder, category: "Files" },
  { name: "Image", icon: Image, category: "Media" },
  { name: "Video", icon: Video, category: "Media" },
  { name: "Music", icon: Music, category: "Media" },
  { name: "Search", icon: Search, category: "Actions" },
  { name: "Filter", icon: Filter, category: "Actions" },
  { name: "Download", icon: Download, category: "Actions" },
  { name: "Upload", icon: Upload, category: "Actions" },
  { name: "Play", icon: Play, category: "Media" },
  { name: "Pause", icon: Pause, category: "Media" },
  { name: "Volume2", icon: Volume2, category: "Audio" },
  { name: "VolumeX", icon: VolumeX, category: "Audio" },
  { name: "Sun", icon: Sun, category: "Weather" },
  { name: "Moon", icon: Moon, category: "Weather" },
  { name: "Cloud", icon: Cloud, category: "Weather" },
  { name: "CloudRain", icon: CloudRain, category: "Weather" },
  { name: "Wind", icon: Wind, category: "Weather" },
  { name: "ShoppingCart", icon: ShoppingCart, category: "Commerce" },
  { name: "CreditCard", icon: CreditCard, category: "Finance" },
  { name: "DollarSign", icon: DollarSign, category: "Finance" },
  { name: "Wallet", icon: Wallet, category: "Finance" },
  { name: "Bookmark", icon: Bookmark, category: "Organization" },
  { name: "Flag", icon: Flag, category: "Organization" },
  { name: "Tag", icon: Tag, category: "Organization" },
  { name: "Tags", icon: Tags, category: "Organization" },
  { name: "Info", icon: Info, category: "Status" },
  { name: "AlertCircle", icon: AlertCircle, category: "Alert" },
  { name: "AlertTriangle", icon: AlertTriangle, category: "Alert" },
  { name: "CheckCircle", icon: CheckCircle, category: "Success" },
  { name: "XCircle", icon: XCircle, category: "Error" },
  { name: "HelpCircle", icon: HelpCircle, category: "Help" },
];
