export const normalizeFilterValue = (value: string): string =>
  value.toLowerCase().trim().replace(/[\s_]+/g, "-");

export const brandLabels: Record<string, string> = {
  autodesk: "Autodesk",
  microsoft: "Microsoft",
  adobe: "Adobe",
  coreldraw: "Coreldraw",
  antivirus: "Antivirus",
  "structural-softwares": "Structural Softwares",
  "architectural-softwares": "Architectural Softwares",
  "billing-software": "Billing Software",
  "accounting-billing": "Billing and Accounting",
  ebook: "Ebook",
  "recovery-softwares": "Recovery Softwares",
  "3d-rendering-software": "3D Rendering Software",
};

export const categoryLabels: Record<string, string> = {
  autocad: "AutoCAD",
  "3ds-max": "3ds MAX",
  revit: "Revit",
  maya: "Maya",
  fusion: "Fusion",
  "navisworks-manage": "Navisworks Manage",
  "inventor-professional": "Inventor Professional",
  "autocad-lt": "AutoCAD LT",
  "aec-collection": "AEC Collection",
  "civil-3d": "Civil 3D",
  "map-3d": "Map 3D",
  "autocad-mechanical": "AutoCAD Mechanical",
  "autocad-electrical": "AutoCAD Electrical",
  "autocad-mep": "AutoCAD MEP",
  "microsoft-365": "Microsoft 365",
  "microsoft-professional": "Microsoft Professional",
  "visio-professional": "Visio Professional",
  "microsoft-projects": "Microsoft Projects",
  server: "Server",
  windows: "Windows",
  "adobe-acrobat": "Adobe Acrobat",
  photoshop: "Photoshop",
  lightroom: "Lightroom",
  "after-effect": "After Effect",
  "premier-pro": "Premier Pro",
  illustrator: "Illustrator",
  "adobe-creative-cloud": "Adobe Creative Cloud",
  "coreldraw-graphics-suite": "Coreldraw Graphics Suite",
  "coreldraw-technical-suite": "Coreldraw Technical Suite",
  "k7-security": "K7 Security",
  "quick-heal": "Quick Heal",
  "hyper-say": "Hyper Say",
  norton: "Norton",
  mcafee: "McAfee",
  eset: "ESET",
  "e-tab": "E-Tab",
  safe: "Safe",
  "sap-2000": "Sap 2000",
  tekla: "Tekla",
  lumion: "Lumion",
  "twin-motion": "Twin Motion",
  "d5-render": "D5 Render",
  "archi-cad": "Archi CAD",
  "sketch-up": "Sketch Up",
  tally: "Tally",
  vyapar: "Vyapar",
  "civil-engineering": "Civil Engineering",
  "ai-prompts": "AI Prompts",
};

export type SortOption = "newest" | "modified" | "oldest" | "name-asc" | "name-desc";

export const sortOptions: { value: SortOption; label: string }[] = [
  { value: "newest", label: "Newest first" },
  { value: "modified", label: "Modified first" },
  { value: "oldest", label: "Oldest first" },
  { value: "name-asc", label: "Name (A-Z)" },
  { value: "name-desc", label: "Name (Z-A)" },
];
